import "./globals.css";

export const metadata = {
  title: "Club Shawayi",
  description: "Generated by Lunar Enterprises",
  // viewport: "width=device-width, initial-scale=1",
};
export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        
        <main>{children}</main>
      </body>
    </html>
  );
}
